sdgwebsite/resources/urls.py
from django.urls import path
from . import views

app_name = 'resources'

urlpatterns = [
    path('article/new/', views.publish_article, name="publish_article"),

    path('article/<str:unique_id>/', views.article_view, name='article_view'),
    path('home/', views.homepage_view, name='homepage_view'),
    path('article/', views.article_home_view, name="article_home_view"),
]

sdgwebsite/sdgwebsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('resource/', include('resources.urls')),

]

sdgwebsite/resources/models.py
from django.db import models
from django.contrib.auth.models import User
import string
import random

# Create your models here.
class Source(models.Model):
    link = models.CharField(max_length=1_000, blank=True, null=True)
    name = models.CharField(max_length=250, blank=True, null=True)

    def __str__(self):
        return self.name

    # TODO could name the link with a function instead of user prompt


class Article(models.Model):
    # blank and null prevent database errors
    title = models.CharField(max_length=250, blank=True, null=True)
    # user saved as author, idk if we should cascade, that will delete the article if the account is
    author = models.CharField(max_length=250, blank=True, null=True)
    # source can have multiple Articles and Article can have multiple Sources
    sources = models.ManyToManyField(Source)
    # automatically records the most recent update
    date_published = models.DateField(auto_now=True)
    # want to have set categories to choose from for sorting purposes
    topic = models.CharField(max_length=100, blank=True, null=True)
    # stores content of article
    content = models.TextField(null=True)
    # stores images for article
    visuals = models.FileField(upload_to='uploads/', null=True)
    # creates unique id for article
    unique_id = models.CharField(max_length=8, default=''.join(random.choices(string.ascii_letters, k=8)))
    def __str__(self):
        return self.title

    # TODO could add functions for sorting


# TODO could add class for visualizations
    

sdgwebsite/resources/forms.py
from django import forms

from .models import Article, Source

class ArticleForm(forms.ModelForm):
    author = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Author..."}))

    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Title..."}))
    topic = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Topic..."}))

    content = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Write article here..."}))
    visuals = forms.FileField(required=False)
    sources = forms.URLField()
    
    class Meta:
        model=Article
        fields=['author', 'topic', 'title', 'content', 'visuals', 'sources']

sdgwebsite/resources/views.py
from django.shortcuts import render, redirect, HttpResponse
from resources.models import Article, Source
from .forms import ArticleForm
from django.contrib import messages
# Create your views here.
def homepage_view(request):
    articles = Article.objects.all()
    context = {"articles": articles}
    return render(request, "homepage.html", context)

    
def article_view(request, unique_id):
    article = Article.objects.filter(unique_id=unique_id)[0]
    sources = article.sources.all()
    context = {"article": article, "sources": sources}
    return render(request, "article.html", context)

def article_home_view(request):
    articles = Article.objects.all().order_by('-date_published')

    context = {"articles": articles}
    return render(request, "articlehome.html", context)

def publish_article(request):
    form = ArticleForm(request.POST or None)
    if form.is_valid():
        # form.save()
        article = Article.objects.create(title=form.cleaned_data.get('title'), 
                                         author=form.cleaned_data.get('author'),
                                         content=form.cleaned_data.get('content'),
                                         visuals=form.cleaned_data.get('visuals'),
                                         topic=form.cleaned_data.get('topic')
                                         )
        article.save()
        return redirect('resources:homepage_view')

    messages.success(request, f'Article published!')
    context = {'form': form}
    return render(request, "publish.html", context)
    # return redirect('resources:hompage_view')

sdgwebsite/templates/article.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type='text/css' href="{% static 'article.css' %}">
    <title>{{article.title}}</title>
  </head>
  <body>
    <header>
      <div class="container">
        <div class="logo">
          <a href="#">Logo</a>
    </header>
    <div class="container">
      <h1 class="title">{{article.title}}</h1>
      <div class="meta">
        <span class="author">{{article.author}}</span>
        <span class="date">{{article.date_published}}</span>
        {%for source in sources%}
        <a href="{{source.link}}">{{source.name}}</a>
        {% endfor %}
      </div>
      <div class="content">
        <p>{{article.content}}</p>
        <p>Additional paragraphs can be added here.</p>
        <img src="image.jpg" alt="Article Image">
        <p>Additional content can be added here as well.</p>
      </div>
    </div>
    <footer>
      <div class="container">
        <p>Copyright ©2022 Luca Zerege</p>
        <ul>
          <li><a href="#">Terms of Service</a></li>
          <li><a href="#">Privacy Policy</a></li>
        </ul>
      </div>
    </footer>
  </body>
</html>

sdgwebsite/templates/articlehome.html
{% load static %}
{% for article in articles %}
<div>
    <a href="{% url 'resources:article_view' article.unique_id %}">
        <h1>{{article.title}} | {{article.topic}}</h1>
        <h3>{{article.author}} | {{article.date_published}}</h3>
    </a>
</div>
{% endfor %}

sdgwebsite/templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <link rel="stylesheet" type='text/css' href="{% static 'homepage_style.css' %}">
        <link rel="icon" type='image/png' href="{% static 'icon.png' %}">

    </head>

    <header>
        SDGsite
    </header>
    <div class="sticky" style="height:50px">
      <div class="header">  
        <h2 style="margin:10px">Home</h2>
      </div>
      
      <div class="header">
        <a class="header" href="{% url 'resources:article_home_view' %}">Articles</a>
      </div>
      
      <div style="float:left; width:10%">
        <link rel="icon" type='image/png' href="{% static 'icon.png' %}">
      </div>
    
    </div>
    
    <body>
      <div class="statement">
        <h1 style="text-align: center; font-size: 40px;">Our Mission</h1>
      </div>
      
      <div>
        <h3 style="font-size: 30px;">
          Goal:
        </h3>
        <p style="width: 20%">To create a website that allows anyone, especially someone with no STEM or political background, to find information about climate change and climate science in understandable, everyday terms.
        </p>
        {% for article in articles %}
        <p>
         {{article.title}}
         {{article.sources}}

        </p>
        {% endfor %}
      </div>
    </body>
</html>

sdgwebsite/templates/publish.html
Publish Article
{% load static %}
<head>
  <link rel="stylesheet" type='text/css' href="{% static 'publish.css' %}">

</head>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class='form-group'>
      <legend class='border-bottom mb-4'>Profile Info</legend>
      {{ form }}
    </fieldset>
      <div class="form-group">
        <button class='btn btn-outline-info' type='submit'>PUBLISH!</button>
      </div>
  <div class="border-top pt-3">
  
  </div>
  
  
  </form>
  